### ISSUE TITLE
Amount of token always off by 600

### ISSUE THREAD

**Issue by esot321c** [rosen-bridge/ui#2] opened 2024-01-02 22:53 UTC
![image](https://github.com/rosen-bridge/ui/assets/86281023/cde5318f-f4a1-402d-8510-6b7158cd682d)

**Comment by mkermani144** [comment] 2024-01-03 07:50
Thanks for bug report.

I pretty sure this is the cause:
https://github.com/rosen-bridge/ui/blob/8068a5392cff6da0405aeddfbbc4312741ea38ed/apps/rosen/app/(bridge)/BridgeForm.tsx#L172-L176

While it should be:
```ts
 getMaxTransferableAmount( 
   amount, 
   sourceField.value, 
   tokenField.value.metaData.type === 'native', 
 ).toString(), 
```

It will get fixed in the next release.

**Comment by mkermani144** [comment] 2024-01-03 09:34
Resolved in https://github.com/rosen-bridge/ui/commit/6d091ce7825c679670d0d93ba4c4554b64b222b7.

**Closed as completed** 2024-01-03 10:48 UTC
